### ISSUE TITLE
Make existing lists work for any number of items

### ISSUE THREAD

**Issue by phylll** [michael-buschbeck/mychs-macro-magic#102]
The `,` operator makes it possible to create lists:

```
!mmm   set list = 1, 2
!mmm   for item in list
!mmm     chat: item: ${item}
!mmm   end for
```

*produces the following output:* 

```
item: 1
item: 2
```

This works predictably as long as the list is created only once, with a set number of elements (whether manually, or by calling a function that returns a list, such as `findattr()`).

However, once I try to manipulate an existing list -- adding to it is the only way possible right now -- I get nested lists:

```
!mmm   set list = 1, 2
!mmm   set list = list, 3
!mmm   for item in list
!mmm     chat: item: ${item}
!mmm   end for
```

*produces the following output:* 

```
item: 1, 2
item: 3
```

With existing MMM features as of 1.19.0, I don't see a way of either avoiding this nesting behavior when manipulating a list (since I cannot explicitly add to a list), or recursively resolving any number of nested levels when reading from the list (which would also be excessively complicated to use every time a script needs to read from a list). The only simple way I've found to do the latter is to output a list in a plain way using `chat: ${list}`, which produces a linear series of comma-separated values. Doesn't help me for internal operations such as `for` loops over list elements, or for more complicated output cases such as whispering each list element to a different player, or prettifying each element with CSS or `highlight()` .

I *assume* that MMM will *require* this nesting behavior to allow for passing lists as individual arguments to a function, so that `do myFunction(list1, "string", number)` won't be resolved into `do myFunction(list1[0], list1[1], list[2], ..., "string", number)` before the function even gets to parse its arguments.

If that assumption is correct, options might be:
1. to add a function to explicitly append a new item to an existing list, such as `set myList = append(myList, newItem)`, which would effectively be more of a combine function that could probably easily be able to combine as many scalars or lists as needed, or at least two arguments that could be either scalars or lists or a mix of both?
2. to add some notation/operator to the more limited effect of appending exactly one item (scalar or list) to an existing list: `set myList[] = newItem` (so if `newItem` was a list, it would be treated as such and added to `myList` as a nested list). This sounds as if it could be needlessly difficult with the current parser.
3. to add a function `islist(var)` that tells the programmer if something is a list already. If I knew that, I could probably write somewhat complicated code to rebuild each list from scratch as soon as it reaches two scalar elements, and thus to avoid nesting where I don't want it.

**Comment by michael-buschbeck** [comment]
All very good observations and suggestions.

The truth of the matter is that making (let alone manipulating) lists has been an afterthought of making _argument_ lists until now. Ultimately, I think general-p purpose lists are an entirely different beast than argument lists, and they deserve better than to be shoehorned into the same set of design choices.

**Argument lists:**
- Each operand produces exactly one element. Otherwise it becomes really hard to see which operand maps to which function parameter, which isn't very programmer-friendly.
- This also means that argument lists may contain undefined values and nested lists (though it _doesn't_ mean those can be arbitrarily nested – it's just "argument list may contain general-purpose list").

**General-purpose lists:**
- Hardly ever does a programming problem call for lists-of-lists, so let's just say that **general-purpose lists are always flat.**
- Undefined values already coerce to empty lists in list context (like when used as the argument for `for`). So let's just say that **general-purpose lists can't contain undefined values.** (I'm not sure yet if this should or shouldn't include `denied` and `unknown`.)

To mitigate the situation where a problem _does_ call for a data structure that represents a list of lists, I'm planning to introduce a concept of "structs" (like JavaScript objects or Perl hashes) – instead of creating a list containing lists, you'd create a list of structs that have a list member (or several).

Thoughts?

**Comment by phylll** [comment]
Makes sense to me! Structs (or tables) will be fun to have since I am already finding workarounds where I'd love to be able to store information in key-value pairs, most often to preserve validated data between the validation and the processing stage of my script, or processed data between the processing and the output stage. Anyway, not super-urgent at all.

For now, having flat general-purpose lists that I'd be able to manipulate (at least in terms of adding one or more items) would be great! I *think* it would be best to allow `denied` and `unknown` as items of such a list for keeping track of and being able to report data access problems to the user. (Also, if MMM allows it, the programmer can easily test for those values and discard them -- while it would be impossible to test for information that MMM has already discarded.)

**Comment by michael-buschbeck** [comment]
Agree with the take on `denied`, `unknown`, and `default` – for rationale I'd add that those special values carry with them and _expectation_ of an actual defined value even if none was to be had.

For the sake of brevity I'm going to call argument lists "args" and general-purpose lists just "list". The comma operator is "comma".

Invariants:
- Lists cannot contain lists.
- Lists cannot contain args.
- Args _can_ contain lists.
- Args cannot contain args.

What happens:
- Comma always returns args. (The result me be converted to list if returned as the final result of an evaluation.)
- `(args, args)` are concatenated into args.
- `(args, val)` and `(val, args)` are concatenated into args regardless of the type of `val` (even undefined).
- Coercing args to args is a no-op.
- Coercing any other value, including lists, to args returns a single-element args.
- Coercing list to list is a no-op.
- Coercing args to list flattens one level of nesting (lists contained in the args are flattened), then removes strictly `undefined` values (but not `denied` etc.).
- Coercing `undefined` to list returns an empty list.
- Coercing any other value to list returns a single-element list.
