### ISSUE TITLE
Potential bug in `senseLogic` or MMM: `chat` function is overwritten with `undef`

### ISSUE THREAD

**Issue by phylll** [michael-buschbeck/mychs-macro-magic#119]
Try this:

- In our TEST game, select two tokens with standard senses, e.g. Yorric MacRathgar and Yerrick MacRothgar.
- From the character sheet "MacroSheet", execute the ability "senseSeeManual". Accept both input prompts unchanged.

My output:

```(From phyllo):
Sehen
Yorric MacRathgar 17
💬 Deinen Augen fällt nichts besonderes auf hier.
Yerrick MacRothgar 14
💬 Deinen Augen fällt nichts besonderes auf hier.
(From Mych's Macro Magic):
🔎 "/w \"Yorric MacRathgar\" Deinen Augen fällt nichts besonderes auf hier." undef
(From Mych's Macro Magic):
During execute, unknown function in expression in script: !mmm do chat❌(playerMessage)
```

The last bit is the original error message we stumbled over during the game last night. The second to last bit is debug code I just added: the value of `playerMessage` and the value of `chat`, the latter of which should be provided in a debug chat context as `(...args) => symbolValue.apply(symbolContext, args)`, I learned.

Why is this happening? I went through the code (abilities `senseSeeManual` and `senseLogic` in the MacroSheet "character", for the above test case) and there are only very simple `combine chat` and `chat:` commands before the line that throws the error. 

With MMM 1.19, the script worked without a hitch -- though we admittedly didn't have it around for very long, so there may be a special set of conditions that just didn't come up before last night.

**Comment by michael-buschbeck** [comment]
Thanks for the comprehensive report! Having a reliable repro case will make this a whole lot easier to fix.

MMM 1.20.0 completely replaced the inner workings of the expression engine, which I'm sure has something to do with this. I'll check it out as soon as possible.

**Comment by michael-buschbeck** [comment]
Minimal repro case:

```
!mmm script
!mmm     combine chat
!mmm     end combine
!mmm     do chat("foo")
!mmm end script
```

> (From Mych's Macro Magic):
> During execute, unknown function in expression in script: !mmm do chat❌("foo")

So it's apparently a failure of `end combine` to properly un-register its temporary replacement of the `chat` function, which it puts into the variables stash.

**Comment by michael-buschbeck** [comment]
The root cause is a subtle change in how context shadowing behaves after the MychExpression rewrite: Previously, an `undef`-valued variable wouldn't have shadowed the corresponding context member – now, it does.

This change triggers the bug because `end combine` never _quite_ cleaned up after itself entirely correctly: Regardless of whether the `chat` variable was `undef` or entirely didn't exist, it left the variables stash with an `undef`-valued `chat` variable in the end. This bit should definitely be fixed, if just to be completely clean about it.

This leaves the question though whether the new context-shadowing behavior should be considered a bug or a bugfix compared to the old behavior. There's currently no way to _delete_ a variable – you can only set it to `undef`.

But arguably, when you do that, you'd expect it to _remain_ `undef` much rather than suddenly have some other value appear in place of the `undef` you set (from context). So I'd argue that the new shadowing behavior has much less potential of being surprising or introducing sudden bugs due to a new MMM context symbol being introduced in a new version. (For example, when the `selected` context symbol was introduced recently, an existing MMM script that used `selected` as a regular variable would still behave predictably even after setting `selected` to `undef`.)

**Comment by michael-buschbeck** [comment]
The `!mmm chat:` command remained unaffected because its context fallback mechanism is separate from the expression engine's (and still looked for `undef` instead of existence).

I can't come up with a particularly compelling reason why I should change this except for consistency with the `chat()` function.

The only possible outcome of aligning the context fallback mechanism of the `chat:` command with symbol lookup in the expression engine is more crashes in case someone sets a variable named `chat`. Maybe a better choice is to make the `chat:` command _more_ robust by allowing only _functions_ to shadow the default context `chat()` function.

**Comment by michael-buschbeck** [comment]
By the way: This...

```
!mmm script
!mmm     set chat = whisperback
!mmm     chat: Whisper!
!mmm end script
```

...does, and should do, exactly what it sounds like. Not sure if it's useful anywhere. (Maybe if we ever get custom functions?)
