### ISSUE TITLE
Parser issue with "." notation to access attributes

### ISSUE THREAD

**Issue by phylll** [michael-buschbeck/mychs-macro-magic#123]
In `if isunknown(var.attr)`, an unknown `var.attr` (where `var` refers to a valid token for which `attr` does not exist) is resolved into an object instead of `unknown` which would be correct, and which happens correctly in `chat: ${var.attr}`, for example.

Test case in our TEST game using the "Finn's Spiderbro" token which is not connected to a character sheet:

```
!mmm script
!mmm   set foe = "-MS7W5j56aYtw9Ry4vZV"
!mmm   if isunknown(?(foe.Gw))
!mmm       chat: /w GM ${foe.name} kennt das Attribut **Gw** nicht. 
!mmm   end if
!mmm end script
```

**Comment by michael-buschbeck** [comment]
Internally, the `foe.Gw` syntax wraps the value retrieved by the (behind-the-scenes) `getattr(foe, "Gw")` call into an object that has `toScalar()` (in order to retrieve the actual value) and `getProperty(key)` (in order to support `foe.Gw.max`).

`isdefault()` and friends never bother to call `toScalar()` when it's present – or more correctly, they don't call `coerceScalar()` on their argument. So what they see is a simple object that's not an `Unknown` etc. instance even if that object wraps one, so they return `false`. Simples!

Fix forthcoming.

**Comment by michael-buschbeck** [comment]
Investigating this has also revealed #125.

**Comment by michael-buschbeck** [comment]
> `isdefault()` and friends never bother to call `toScalar()` when it's present – or more correctly, they don't call `coerceScalar()` on their argument. So what they see is a simple object that's not an `Unknown` etc. instance even if that object wraps one, so they return `false`. Simples!

Careful though: `Unknown` etc. objects use `toScalar()` to return `undef`.
