### ISSUE TITLE
Introduce a way to check list membership

### ISSUE THREAD

**Issue by phylll** [michael-buschbeck/mychs-macro-magic#147]
Would be great to be able to check if a list contains an item or several items that is/are equal to something I am looking for. For https://github.com/phylll/mychs-macro-magic/issues/21, I will need this several times and implementing similar-but-not-identical search loops several times without being able to define a function is just bound to produce bugs and maintenance hassles, and will lead to bloated code. So I'm hoping there is not just a more elegant but maybe even quite a simple solution of adding a function or an operator to MMM itself?

Imaginary syntax example:
```
set stavesDefendAgainst = "One-handed sword", "Stave", "Polearm", "Parry weapon", "Thrust weapon", "Spear"
if attackWeaponType in stavesDefendAgainst
  chat: My quarterstaff (member of the category staves) is finally good for something! Take this, overconfident attacker!
else 
  chat: Against this weapon my quarterstaff is sadly useless, so I'm down to a regular defense.
end if
```

Instead of this `in` operator, a function that takes the list and the item(s) to find as arguments would do equally well, I guess.

**Comment by michael-buschbeck** [comment]
Ever since #85 I've wanted to introduce an operator that leverages the new engine's central improvement: that it produces an evaluator function (for every subexpression) instead of a result.

That makes it possible to create a `where` operator:

```
!mmm set nearly_dead = selected where item.HP < 5
```

Combined with empty lists coercing to bool `false` this would also make for a versatile list-contains operator:

```
!mmm if stavesDefendAgainst where item eq attackWeaponType
```

That said, a simple `in` operator that compares for string equality would also be easy to add. (We'd have to decide on a fixed type – string, number, or whatever – to do the comparison in.)

**Comment by phylll** [comment]
Your `where` operator sounds a lot more versatile and powerful than just the `in` operator, so if `where` is feasible to implement, I', all for it!

**Comment by michael-buschbeck** [comment]
The `list where condition` idea is discussed in #110.
