### ISSUE TITLE
Provide access to enemy token's endurance (AP in German Midgard)

### ISSUE THREAD

**Issue by phylll** [michael-buschbeck/mychs-macro-magic#19]
If it should be possible to automatically calculate the attack modifiers for enemy exhaustion (as in Midgard combat rules, which make attacks easier by 4 if the target's endurance is 0), PCs and their macros need access to other tokens' AP attribute. This access is currently denied, which makes some sense in terms of the overall permissions logic (I cannot precisely "see" an enemy's endurance). At the same time, I _should_ be able to see major levels of endurance loss, such as the total exhaustion that leaves an enemy exceptionally vulnerable (as in the 0 AP case).

**Comment by michael-buschbeck** [comment]
I'm envisioning a way in which a GM can define custom "public attributes" for any specific character or a whole class of characters.

Not sure how to best let them phrase this though. Here's a first shot, brainstorming-style:

| Line | Commands
| 1 | _!mmm_ **publish attributes where** getattr(character, "name") contains "Orc"
| 2 | _!mmm_     **if** getattr(character, "AP") > 0
| 3 | _!mmm_         **publish attribute** AttackBonus = 0
| 4 | _!mmm_     **else**
| 5 | _!mmm_         **publish attribute** AttackBonus = 4
| 6 | _!mmm_     **end if**
| 7 | _!mmm_ **end publish**

And with that, every "Orc Warrior #17" would have an implicit attribute named `AttackBonus` that every player can read.

The **publish** block would automatically hook into the API's on-attribute-change event to make sure this block is re-run automatically whenever an "Orc" character appears or has his/her/their (other) attributes changed.

This obviously begs the question inasmuch as *where* these lines should be (because clearly the GM shouldn't have to manually execute them whenever the game starts) – but I had already been thinking along the lines of allowing players and GMs to persistently register MMM scripts for automatic execution when the script sandbox starts, maybe through a per-player specially-named macro that MMM loads and runs after MMM itself has initialized.

**Comment by michael-buschbeck** [comment]
Actually, brainstorming a bit further, maybe it's best to split the above into separate, orthogonal ideas:

1. Allow character controllers (GM for all, but also player for theirs) to selectively allow access to certain otherwise hidden character attributes. That way, the simplest thing a GM could do is just let everyone access every Orc's AP directly (but nothing else).
2. Allow scripts to auto-run at sandbox start (so the permission control command doesn't need to be re-executed manually over and over again).
3. Allow scripts to hook into on-attribute-changed events so they can `setattr()` whatever character attributes they like, private or public. (That would include scripts that automatically update certain token badges etc.)

**Comment by phylll** [comment]
Trying to think a few steps ahead along the current road of automation: once we've mastered our attacks themselves, we (or our busy GM) might not want those attack scripts to stop with telling us about the successful roll and notional damage. We could consider including the target's defense roll and executing the results (accessing armor, endurance and health) in the original attack script (provided the GM wanted to give player scripts access to those). I have no idea if we'd want to go there, but it might be useful as a scenario to make your architecture changes robust to crazy future ideas.

**Comment by michael-buschbeck** [comment]
Hah! I like that way of thinking.

Maybe that calls for being able to send structured messages to the GM – some technical representation of "Finn successfully attacked Orc Warrior 17 with an attack roll of 26 for 8 points of damage" that a GM-controlled script could…

1) pick up automatically,
2) display in a human-readable form for the GM to eyeball, and
3) react to under the GM's control – by doing a defense roll etc. and apply the outcome to Orc Warrior 17, for example.

**Comment by phylll** [comment]
In addition to #36, another field that it would be good to have the option of making accessible if we ever went there (boy do I hope the grammar works here) is `Grad`, for attack/magic scripts calculating experience points.

**Comment by michael-buschbeck** [comment]
That's a tricky one because we don't have a conceptual workaround like we had for AP (the bar graph, which I actually appreciate having as a player too).

We could…
- Make this field (or any other) generally public.
- Devise a scheme to grant permission to this field for other players – e.g. if there's a custom attribute `Grad_permission_view` it's interpreted as a comma-separated list of player IDs (or `all`) that can read this attribute.

Personally, the very concept of having a spell's endurance cost depend on the target's level makes _some_ sense to me, but the gameplay mechanics of it doesn't ("you've succeeded but, oops!, you're out eleventythree endurance points now that you barely had anymore"). 

It'd makr more sense to me if the spellcaster had to _inch_ their way towards either success or give up on the way: "You've successfully focused your mana [rolled success], but you can still feel the target resisting. Do you want to invest another point of endurance? – Ah, you can feel their resistance become weaker but it's still there… another point, or give up? …"

**Comment by phylll** [comment]
I agree on the game mechanics, and the accessibility issue is not urgent at all -- I've got a workaround by placing this logic in GM-controlled scripts. Just something that came to mind since I saw the issue was still open, for you to consider along with `AP` and `Gestalt` if or when you might implement a cleaner / better solution for these access issues.

**Comment by phylll** [comment]
Since our library code is running with GM rights, this is effectively not an issue any longer.
