### ISSUE TITLE
`[object Object]` is returned when trying to access non-existent `token_id` for a player object

### ISSUE THREAD

**Issue by phylll** [michael-buschbeck/mychs-macro-magic#197]
> [object Object] appearing anywhere user-facing is also a bug. I'm aware of that happening in debug outputs but not anywhere else yet – is this something you can reproduce?

Now, yes -- when trying to get a `token_id` from a sender without a token:

```
!mmm script
!mmm   set id = "phyllo (GM)".token_id
!mmm   if isunknown(id) or isdenied(id)
!mmm     do whisperback("Token ID invalid: '" & id & "' - " & getreason(id))
!mmm   end if
!mmm end script
```

Output:

> **(From Mych's Macro Magic):**
> Token ID invalid: '[object Object]' - Character or token phyllo (GM) inaccessible

**Comment by michael-buschbeck** [comment]
Simpler repro case:

```
!mmm chat: ${foo.bar & ""}
```

Seems like the ad-hoc wrapper (that only exists to add support for `.max`) is missing a stringifier.

**Comment by michael-buschbeck** [comment]
This is fixed, but the fix doesn't really improve user experience in the sample case: `default`. `unknown`. and `denied` now stringify to an empty string (as they're documented), so instead of `[object Object]` you'll simply see nothing between the quotes.

What's really needed for this use case is a markup-preserving concatenation operator. (I think there may be an open issue for that already?)
