### ISSUE TITLE
Base dice roll on variable

### ISSUE THREAD

**Issue by alie2n** [michael-buschbeck/mychs-macro-magic#23]
It would be nice if we could base a dice roll on a variable something like:
```
set DamageValue=1d6+1
set damage=[[${DamageValue}]]
chat: Damage was ${damage}
```

In Midgard Character Sheet you can reference the weapon damage using:
getattr(sender, findattr(sender, "Angriff", "Waffe", UsedWeapon, "WaffeSchaden"))

And I would like to do:
```
!mmm script
!mmm   set UsedWeapon = "Streitaxt Hu Gadarn"
!mmm   set DamageBonus = getattr(sender, findattr(sender, "Angriff", "Waffe", UsedWeapon, "WaffeEfSchB"))
!mmm   set DamageValue = getattr(sender, findattr(sender, "Angriff", "Waffe", UsedWeapon, "WaffeSchaden"))
!mmm   set DamageRoll = [[${DamageValue}]]
!mmm   set damage= DamageRoll + DamageBonus
!mmm   chat: /w Schaden: DV ${DamageValue}; DR ${DamageRoll}; D ${damage}
!mmm end script
```

**Comment by michael-buschbeck** [comment]
This request makes complete sense. Much more sense than Roll20's bass-ackward way of handling macros.

The reason it's not in already is thanks to Roll20 executing and replacing all [[...]] long before MMM gets to see the line – and while MMM *can* construct some "[[...]]" at script runtime and send it to chat, *that* roll will be executed asynchronously long *after* the MMM script has completed running.

That said, I've opened #18 to investigate a way to solve this. If this works out, we'll be able to construct rolls in-script, roll them, and continue the script with the roll's result.

**Comment by michael-buschbeck** [comment]
It looks like I'm simply going to provide a `roll(expr)` function:

| Line | Command
| 1 | _!mmm_ **set** attackRollExpr = getattr(sender, findattr(…, "attack"))
| 2 | _!mmm_ **set** attackRoll = roll(attackRollExpr)
| 3 | _!mmm_ **if** attackRoll >= 20
| 4 | …

**Comment by michael-buschbeck** [comment]
Known (and unfortunately probably unsolvable issue): Syntax errors in the roll expression just silently stop the script.

Background: `roll(expr)` operates by sending `expr` to the Roll20 chat engine as `/roll expr` and then waiting for a callback to receive the results. In case of an error, Roll20's chat engine just spams the API sandbox log with an error message (a technical representation of the same you'd see in the chat box) but never invokes the callback or any other event handler I'm aware of.

Fortunately, the difference is really just whether the user gets a useful error message or not. (Though on second thought, in keeping with the behavior of other MMM functions, `roll(expr)` should probably just return undef if `expr` is broken.)

To mitigate this, I could conceivably impose a timeout on receiving the roll result. That raises the question of *how long* that timeout should be, of course, because we certainly also don't want to miss actual roll results just because it's a Friday evening.

**Comment by alie2n** [comment]
Perhaps you could check `expr` via regexp for validity and only call the Roll20 chat engine if the `expr` is valid.
I think something like this could be sufficient: [0-9]+[dD][0-9]+[+0-9]* (given the usual dice rolls 1d6, 1d6+2, 5d20+1)

**Comment by michael-buschbeck** [comment]
You're not wrong, of course, and a simple syntax check like that would probably fit *our* needs – but I'm loathe to remove entire swaths of potential functionality just to make error diagnostics a bit nicer. And given that Roll20's full dice roll syntax is the work of the devil when he was sitting at home, bored to death in Corona lockdown, and just done writing the [Malbolge](https://en.wikipedia.org/wiki/Malbolge) Specs, writing a full Roll20 dice roll syntax validator is a bit daunting.

(Also, are we sure it fits our needs? Some of these "success roll" character sheer attributes can get pretty involved with sums and parentheses and whatnot.)
