### ISSUE TITLE
Facilitate sending attack results to GM characters in an automated way

### ISSUE THREAD

**Issue by michael-buschbeck** [michael-buschbeck/mychs-macro-magic#29]
Trying to think a few steps ahead along the current road of automation: once we've mastered our attacks themselves, we (or our busy GM) might not want those attack scripts to stop with telling us about the successful roll and notional damage. We could consider including the target's defense roll and executing the results (accessing armor, endurance and health) in the original attack script (provided the GM wanted to give player scripts access to those). I have no idea if we'd want to go there, but it might be useful as a scenario to make your architecture changes robust to crazy future ideas.

_Originally posted by @phylll in https://github.com/michael-buschbeck/mychs-macro-magic/issues/19#issuecomment-771992953_

**Comment by michael-buschbeck** [comment]
Hah! I like that way of thinking.

Maybe that calls for being able to send structured messages to the GM – some technical representation of "Finn successfully attacked Orc Warrior 17 with an attack roll of 26 for 8 points of damage" that a GM-controlled script could…

1) pick up automatically,
2) display in a human-readable form for the GM to eyeball, and
3) react to under the GM's control – by doing a defense roll etc. and apply the outcome to Orc Warrior 17, for example.

_Originally posted by @michael-buschbeck in https://github.com/michael-buschbeck/mychs-macro-magic/issues/19#issuecomment-772012133_

**Comment by michael-buschbeck** [comment]
Moving this discussion into a separate issue to maintain focus (on both sides).

Brainstorming how to "send attack results to GM characters" (or actually any other characters)...

General considerations:
- Sending attack messages should be **safe for the recipient:** Anyone can send an attack message, but it's up to the recipient to react (or not).
- Flooding a target character with attacks should be impossible: Only one (the most recent) attack per attacker and target (attackee?) is stored. If the player character re-rolls their attack before the GM reacted to it, the update will replace the still-pending previous attack.
- Use existing Roll20 API functionality where possible – e.g. **custom character attributes** to store per-character data (which comes with the added benefit of firing an event on change that the recipient can pick up); **token status markers** to tell the GM that a character has a successful attack waiting for them to react to.

How it could work, technically:

- ***Finn*** (a player character) attacks ***Orc Warrior*** (a GM-controlled NPC).
- Finn's **attack script**...
  - Determines that Finn has managed a successful hit on Orc Warrior with an attack roll of 23 for 5 points of damage.
  - Executes a yet-to-be-named MMM command that safely records the command in a custom attribute in Orc Warrior's character sheet:
    - Custom attribute name: Fixed namespace prefix `MMM` & type `attack` & attacker character ID
    - Custom attribute value: Data structure (JSON?) that includes `attackRoll` and `damage`
- GM's **attack pick-up script**...
  - Gets notified of the attribute change (per the existing Roll20 event mechanism) somehow exposed in MMM
  - Adds a "Incoming damage!"-type token status marker that has the total incoming damage (from all yet-unhandled attacks) displayed on it
- GM can select Orc Warrior and run their **attack response script**, which...
  - Rolls defense for Orc Warrior for each individual attack (against `attackRoll`)
  - Removes each of Orc Warrior's custom `MMM` & `attack` & attacker ID custom attributes in turn as they are processed
  - Calculates Orc Warrior's effective HP and EP loss, taking their armor and whatnot into account
  - Updates Orc Warrior's HP and EP (and potentially adds a blood splat on top of them if HP<0)
  - Sends a moody message to chat, narrating all of this

That would require the following MMM-side support:
- MMM command to put these special "message" attributes into other characters' attributes.
- MMM construct to iterate over these special "message" attributes of an own character (and *optionally* remove them in turn).
- MMM construct to automatically run pre-defined script code when these "message" attributes change.
- MMM command to set status markers on tokens – see *Support attribute access to `status_`… token properties* #12

**Comment by phylll** [comment]
As you initially say but haven't picked up in the technical brainstorming yet, as an alternative to launching the attack response script, the GM would need a way of dismissing an attack (e.g. erroneously executed by the attacker), that is, simply removing that attack payload from the target. It will also be useful (definitely for debugging and development) to be able to clear an entire NPC of MMM attack transmission data.

**Comment by michael-buschbeck** [comment]
Good point – I wasn't explicit about this.

My thinking is that given that attack "messages" are stored in custom character attributes, the existing Roll20 "Attributes & Abilities" tab could serve to look at, remove, and perhaps even change (for debugging and testing) these messages. (I'm kind of assuming it's a general Roll20 character sheet feature, not just a Midgard one.)

Granted, the attributes half of the "Attributes & Abilities" character sheet tab isn't a *great* UI by any standard and certainly not for attributes whose values are longer than approximately a finger's width, but I'm hoping it'll do.

**Comment by phylll** [comment]
What I meant was not for debugging or occasional cleanup, but for the GM's in-session management to avoid getting flooded in case of erroneous attack rolls, stupid players or buggy attack scripts on the player side. I imagined this not as something very complicated -- simply an option for the GM to react to any particular attack by dismissing it rather than defending against it, in which case the critter's relevant attributes would be cleared.

Two other thoughts:

1. An attack on an NPC does not *have* to be transmitted via the NPC's character sheet. It might be simpler and safer, permission-wise, to store the attack data in the attacking PC's character sheet, as long as the GM's battle management script is somehow notified (which seems, by your description, to be possible in the same way regardless which token or character is affected by the status change). Attack data would have to contain the target id, of course.
2. I could imagine it becoming a bit tedious (under the newly comfortable standards of GMing MMM-supported battles) for the GM to click on every NPC and select its defense script in turn. How about the GM's battle management script (what you've called the attack pickup script) were to generate a [Chat Menu](https://wiki.roll20.net/Chat_Menus) for the GM which would provide a neat list of incoming attacks on each visible NPC, each with a link to dismiss or defend?

**Comment by phylll** [comment]
A simplified version of this is working now; implemented in the [dev/mgd/attack-scripts-experience](https://github.com/phylll/mychs-macro-magic/tree/dev/mgd%2Fattack-scripts%2Fexperience) branch, since it turned out I couldn't implement the experience tracker our GM requested without having at least basic data about each attack passed to the `defense` script. It's not as robust as what we brainstormed here, but it works in the TEST game so far, without a JSON data structure, simply by using lots of different attributes in a universally accessible storage character sheet.

**Comment by phylll** [comment]
So I'm wondering weather it's worth trying to implement more of the above brainstorming, or if we better stick to my current quick-and-dirty solution for the time being, until we can use a structured datatype instead of lots of individual attributes?

What's different in the current solution (TEST game) to the above concept:
- Data is stored in a dummy character sheet that is neither the PC nor the NPC sheet, and which is available for reading and writing to everyone.
- Data is stored in individual attributes per value (since we don't have a structured data type). I already have 8 values I need per attack to implement present functionality.
- No status markers and no automated recognition that an attack happened. Instead, the attack is reported as usual in the chat and the data is (silently) stored in those attributes. When (and only when) the player whose character/NPC was attacked launches their defense script, the stored data is retrieved and used to execute the defense and its consequences (loss of health, endurance etc.). 
- The data exchange attributes themselves are not personalized to each character as envisaged earlier. Instead, the attacking and the defending token IDs are stored as part of it. Upside: No token can suffer from the wrong attack, and if relevant data is missing, the defense script stops and demands manual data entry (or repeating the attack). Downside: There is only one set of exchange attributes, storing only the last attack that happened in the game. Any attack is therefore easily overwritten by the trigger happy player who is next in line and didn't wait for the GM to run his NPC's defense script. If that happens, the data is all in the chat & can be reentered manually, but that's not great in terms of UX.

Options (am I missing anything?):
- Leave as is for adding a more sophisticated option once it's easier to manage complicated data structures.
- Redefine attributes to include the attacker and target token IDs if such long attribute names are permitted: probably possible to implement (but how to hand over the attacker ID in the first place?), will clutter the exchange sheet with potentially many times 8 attributes that are never deleted (existing clean up script won't work as easily) but avoid most overwrite accidents. 
- Add defense trigger chat menu for GM to make it easier to defend for the correct NPC token (works only if every NPC character sheet has a defense config script under a standard name stored as an ability -- a requirement we're hoping to avoid to make our GM's life easier)

**Comment by phylll** [comment]
This is actually done -- if you're satisfied with the script-level (rather than MMM-level) solution we have, we could close this issue.

**Comment by michael-buschbeck** [comment]
The script-level solution you've implemented seems solid – I'll close this.
